language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./composer.phar install --dev --prefer-source

script:
  - phpcs ./src/ --standard=PSR2 --extensions=php --ignore=*/vendor/* --report=summary --encoding=UTF-8
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist
