language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php ./composer.phar install --dev --prefer-source

script:
  - ./vendor/bin/phpcs src/ --standard=PSR2 --report=summary
  - ./vendor/bin/phpcs tests/ --standard=PSR2 --report=summary
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist
